name: Kata Containers CoCo Stability Tests Weekly
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  kata-containers-ci-on-push:
    uses: ./.github/workflows/ci-weekly.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: "weekly"
      tag: ${{ github.sha }}-weekly
      target-branch: ${{ github.ref_name }}
    secrets: inherit
